{{- if not .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multirepo-demo-service.fullname" . }}
  labels:
    {{- include "multirepo-demo-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "multirepo-demo-service.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multirepo-demo-service.fullname" . }}-canary
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multirepo-demo-service.labels" . | nindent 4 }}
    service-type: canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "multirepo-demo-service.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multirepo-demo-service.fullname" . }}-stable
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multirepo-demo-service.labels" . | nindent 4 }}
    service-type: stable
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "multirepo-demo-service.selectorLabels" . | nindent 4 }}
{{- end }}